### ISSUE TITLE
Error syntax in VectorPipeline crash operator

### ISSUE THREAD

**Issue by zvlb** [kaasops/vector-operator#74]
If in VectorPipeline set:
```json
transforms: null
```
Vector Operator has error:
```
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x14dff30]

goroutine 365 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.2/pkg/internal/controller/controller.go:118 +0x1f4
panic({0x16858e0, 0x263fc00})
	/usr/local/go/src/runtime/panic.go:838 +0x207
github.com/kaasops/vector-operator/controllers/factory/config.getSources({0x1adba80, 0xc0007d11e0}, {0x0, 0x0, 0x0?})
	/workspace/controllers/factory/config/config_build.go:202 +0x2b0
github.com/kaasops/vector-operator/controllers/factory/config.(*Builder).getComponents(0x96?)
	/workspace/controllers/factory/config/config_build.go:132 +0x15e
github.com/kaasops/vector-operator/controllers/factory/config.(*Builder).generateVectorConfig(0xc0007bbac0)
	/workspace/controllers/factory/config/config_build.go:110 +0xc9
github.com/kaasops/vector-operator/controllers/factory/config.(*Builder).GetByteConfigWithValidate(0xc00066dac0)
	/workspace/controllers/factory/config/config_build.go:80 +0x33
github.com/kaasops/vector-operator/controllers/factory/config.ReconcileConfig({0x1ad50b8, 0xc00090d3b0}, {0x1ada590, 0xc0005cf400}, {0x1adba80, 0xc0007d11e0}, 0xc00066dc90)
	/workspace/controllers/factory/config/config.go:35 +0xd2
github.com/kaasops/vector-operator/controllers.(*PipelineReconciler).Reconcile(0xc000411340, {0x1ad50b8, 0xc00090d3b0}, {{{0xc0008607a0?, 0x10?}, {0xc0003f2630?, 0x40d787?}}})
	/workspace/controllers/pipeline_controller.go:95 +0x508
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x1ad5010?, {0x1ad50b8?, 0xc00090d3b0?}, {{{0xc0008607a0?, 0x17c6080?}, {0xc0003f2630?, 0x4041f4?}}})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.2/pkg/internal/controller/controller.go:121 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000597f40, {0x1ad5010, 0xc0000c9540}, {0x16f1a00?, 0xc000b28760?})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.2/pkg/internal/controller/controller.go:320 +0x33c
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000597f40, {0x1ad5010, 0xc0000c9540})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.2/pkg/internal/controller/controller.go:273 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.2/pkg/internal/controller/controller.go:234 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.2/pkg/internal/controller/controller.go:230 +0x325
```

**Comment by zvlb** [comment]
fixed
